<a href="https://colab.research.google.com/github/shaikhshoaib/DSSUMIT_2020/blob/master/DS_DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [317]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [318]:
df_train = pd.read_csv('train.csv')
#df_train = df_train[df_train.race != '?']
df_test = pd.read_csv('test.csv')
#df_test = df_test[df_test.race != '?']

In [319]:
df_train['tel_9'].describe()

count     14696
unique      512
top         428
freq       1026
Name: tel_9, dtype: object

In [320]:
print(df_train['tel_12'].value_counts())
print(df_test['tel_12'].value_counts())

9     8448
7     1344
8     1297
6     1259
5     1236
4      659
3      306
2      104
1       18
16      14
10       3
14       2
13       2
11       2
15       1
12       1
Name: tel_12, dtype: int64
9    2864
5    1232
8     952
6     946
7     909
4     558
3     339
2     141
1      29
Name: tel_12, dtype: int64


In [321]:
#df_train['tel_49'].value_counts()
df_train['race'].replace({'?': 'Other'}, inplace=True)
df_test['race'].replace({'?': 'Other'}, inplace=True)

In [322]:
#df_train['tel_9'].replace({'V54': np.nan,'V55': np.nan,'V57': np.nan,'V58': np.nan}, inplace=True)
#df_train['tel_9'].replace({'V53': np.nan, 'V54': np.nan,'V55': np.nan,'V57': np.nan,'V58': np.nan, 
                           #'V60': np.nan, 'V71': np.nan, '?': np.nan}, inplace=True)

In [323]:
df_train['tel_9'].value_counts()

428    1026
414     792
486     587
786     536
410     462
       ... 
660       1
164       1
135       1
52        1
V63       1
Name: tel_9, Length: 512, dtype: int64

In [324]:
print(df_train['race'].value_counts())
print(df_test['race'].value_counts())

Caucasian          11216
AfricanAmerican     2543
Other                556
Hispanic             278
Asian                103
Name: race, dtype: int64
Caucasian          5776
AfricanAmerican    1680
Other               294
Hispanic            170
Asian                50
Name: race, dtype: int64


In [325]:
X_train = df_train[['race', 'gender', 'age', 'time_in_hospital', 'tel_3', 'tel_4', 'tel_5', 'tel_12', 'tel_42' ,'tel_49']].values
X_test = df_test[['race', 'gender', 'age', 'time_in_hospital', 'tel_3', 'tel_4', 'tel_5', 'tel_12', 'tel_42' ,'tel_49']].values
#X_train = df_train[['race', 'gender', 'age', 'weight']].values
#X_test = df_test[['race', 'gender', 'age', 'weight']].values
y_train = df_train.iloc[:,-1].values
#print(np.unique(X_train[:,3], return_counts=True))
#print(np.unique(X_test[:,3], return_counts=True))

In [326]:
print(len(X_train))
print(np.unique(y_train, return_counts=True))

14696
(array([0, 1]), array([ 1489, 13207]))


In [327]:
from sklearn.impute import SimpleImputer

#imputer_1 = SimpleImputer(missing_values=np.nan, strategy='mean')

#imputer_1.fit(X_train[:,4:5])
#X_train[:,4:5] = imputer_1.transform(X_train[:,4:5])
#imputer.fit(X_train[:,3:4])
#X_train[:,3:4] = imputer.transform(X_train[:,3:4])

#imputer_1.fit(X_test[:,4:5])
#X_test[:,4:5] = imputer_1.transform(X_test[:,4:5])
#imputer.fit(X_test[:,3:4])
#X_test[:,3:4] = imputer.transform(X_test[:,3:4])

In [328]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

col_trns = ColumnTransformer([('encoder', OneHotEncoder(sparse=False), [0,8,9])], remainder='passthrough')
lab_enc = LabelEncoder()

X_train = np.array(col_trns.fit_transform(X_train))
#X_train[:,-4] = lab_enc.fit_transform(X_train[:,-4])
#X_train[:,-3] = lab_enc.fit_transform(X_train[:,-3])
X_train[:,-6] = lab_enc.fit_transform(X_train[:,-6])
X_train[:,-7] = lab_enc.fit_transform(X_train[:,-7])
#X_train = X_train[:,1:]

X_test = np.array(col_trns.fit_transform(X_test))
#X_test[:,-4] = lab_enc.fit_transform(X_test[:,-4])
#X_test[:,-3] = lab_enc.fit_transform(X_test[:,-3])
X_test[:,-6] = lab_enc.fit_transform(X_test[:,-6])
X_test[:,-7] = lab_enc.fit_transform(X_test[:,-7])
#X_test = X_test[:,1:]

In [329]:
print(X_test[0])
print(len(X_test[0]))

[0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0 6 4 60 6 22 7]
19


In [330]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy')
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [331]:
#print(classifier.predict([[0, 1, 0, 0, 0, 0, 1, 5, 4, 1]]))

In [332]:
test_pred = classifier.predict(X_test)
print(test_pred.reshape(len(test_pred), 1))
print(np.unique(test_pred, return_counts=True))

[[1]
 [1]
 [0]
 ...
 [0]
 [0]
 [1]]
(array([0, 1]), array([1613, 6357]))


In [333]:
enc_id = df_test['encounter_id']
submission = pd.DataFrame({
              "encounter_id": enc_id, 
              "diabetesMed": test_pred})
#submission = submission[['diabetesMed', 'encounter_id']]
print(submission)

      encounter_id  diabetesMed
0         97074168            1
1         38255910            1
2         36573714            0
3         73972230            1
4         68202342            0
...            ...          ...
7965      86749284            1
7966     135741342            1
7967      65660634            0
7968      73248582            0
7969      48791304            1

[7970 rows x 2 columns]


In [334]:
#submission.to_csv('submission_test.csv', index=False)