In [14]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.tree import DecisionTreeClassifier
#import matplotlib.pyplot as plt

In [15]:
df_train = pd.read_csv('train.csv')
#df_train = df_train[df_train.race != '?']
df_test = pd.read_csv('test.csv')
#df_test = df_test[df_test.race != '?']

In [16]:
df_train['race'].replace({'?': 'Other'}, inplace=True)
df_test['race'].replace({'?': 'Other'}, inplace=True)

In [17]:
X_train = df_train[['race', 'gender', 'age', 'time_in_hospital', 'tel_48', 'tel_49']].values
X_test = df_test[['race', 'gender', 'age', 'time_in_hospital', 'tel_48', 'tel_49']].values
#X_train = df_train[['race', 'gender', 'age', 'weight']].values
#X_test = df_test[['race', 'gender', 'age', 'weight']].values
y_train = df_train.iloc[:,-1].values

In [18]:
from sklearn.impute import SimpleImputer

#imputer = SimpleImputer(missing_values='?', strategy='most_frequent')

#imputer.fit(X_train[:,0:1])
#X_train[:,0:1] = imputer.transform(X_train[:,0:1])
#imputer.fit(X_train[:,3:4])
#X_train[:,3:4] = imputer.transform(X_train[:,3:4])

#imputer.fit(X_test[:,0:1])
#X_test[:,0:1] = imputer.transform(X_test[:,0:1])
#imputer.fit(X_test[:,3:4])
#X_test[:,3:4] = imputer.transform(X_test[:,3:4])

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

col_trns = ColumnTransformer([('encoder', OneHotEncoder(sparse=False), [0,4,5])], remainder='passthrough')
lab_enc = LabelEncoder()

X_train = np.array(col_trns.fit_transform(X_train))
#X_train[:,-4] = lab_enc.fit_transform(X_train[:,-4])
X_train[:,-2] = lab_enc.fit_transform(X_train[:,-2])
X_train[:,-3] = lab_enc.fit_transform(X_train[:,-3])
X_train = X_train.astype(np.float32)
#X_train = X_train[:,1:]

X_test = np.array(col_trns.fit_transform(X_test))
#X_test[:,-4] = lab_enc.fit_transform(X_test[:,-4])
X_test[:,-2] = lab_enc.fit_transform(X_test[:,-2])
X_test[:,-3] = lab_enc.fit_transform(X_test[:,-3])
X_test = X_test.astype(np.float32)
#X_test = X_test[:,1:]

In [20]:
print(X_train[0])

[0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 8. 6.]


In [21]:
ann = tf.keras.models.Sequential()

In [22]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [23]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [24]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [25]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [26]:
ann.fit(X_train, y_train, batch_size=32, epochs=25)

Epoch 1/25
460/460 [==============================] - 1s 1ms/step - loss: 0.3694 - accuracy: 0.8976
Epoch 2/25
460/460 [==============================] - 1s 1ms/step - loss: 0.2681 - accuracy: 0.8987
Epoch 3/25
460/460 [==============================] - 1s 1ms/step - loss: 0.2423 - accuracy: 0.8987
Epoch 4/25
460/460 [==============================] - 1s 1ms/step - loss: 0.2373 - accuracy: 0.8987
Epoch 5/25
460/460 [==============================] - 1s 1ms/step - loss: 0.2357 - accuracy: 0.8987
Epoch 6/25
460/460 [==============================] - 1s 1ms/step - loss: 0.2345 - accuracy: 0.8987
Epoch 7/25
460/460 [==============================] - 1s 1ms/step - loss: 0.2341 - accuracy: 0.8987
Epoch 8/25
460/460 [==============================] - 1s 1ms/step - loss: 0.2337 - accuracy: 0.8987
Epoch 9/25
460/460 [==============================] - 1s 1ms/step - loss: 0.2333 - accuracy: 0.8987
Epoch 10/25
460/460 [==============================] - 1s 1ms/step - loss: 0.2331 - accuracy: 0.8987

In [27]:
test_pred = ann.predict(X_test)
test_pred = np.where(test_pred > 0.5, 1, 0)
print(test_pred.reshape(len(test_pred), 1))
print(np.unique(test_pred, return_counts=True))

[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
(array([0, 1]), array([   2, 7968]))
