In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
df_train = pd.read_csv('train.csv')
#df_train = df_train[df_train.race != '?']
df_test = pd.read_csv('test.csv')
#df_test = df_test[df_test.race != '?']

In [23]:
df_train['race'].replace({'?': 'Other'}, inplace=True)
df_test['race'].replace({'?': 'Other'}, inplace=True)

In [24]:
X_train = df_train[['race', 'gender', 'age', 'time_in_hospital', 'tel_12', 'tel_42' ,'tel_49']].values
X_test = df_test[['race', 'gender', 'age', 'time_in_hospital', 'tel_12', 'tel_42' ,'tel_49']].values
#X_train = df_train[['race', 'gender', 'age', 'weight']].values
#X_test = df_test[['race', 'gender', 'age', 'weight']].values
y_train = df_train.iloc[:,-1].values

In [25]:
from sklearn.impute import SimpleImputer

#imputer = SimpleImputer(missing_values='?', strategy='most_frequent')

#imputer.fit(X_train[:,0:1])
#X_train[:,0:1] = imputer.transform(X_train[:,0:1])
#imputer.fit(X_train[:,3:4])
#X_train[:,3:4] = imputer.transform(X_train[:,3:4])

#imputer.fit(X_test[:,0:1])
#X_test[:,0:1] = imputer.transform(X_test[:,0:1])
#imputer.fit(X_test[:,3:4])
#X_test[:,3:4] = imputer.transform(X_test[:,3:4])

In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

col_trns = ColumnTransformer([('encoder', OneHotEncoder(sparse=False), [0,5,6])], remainder='passthrough')
lab_enc = LabelEncoder()

X_train = np.array(col_trns.fit_transform(X_train))
#X_train[:,-4] = lab_enc.fit_transform(X_train[:,-4])
X_train[:,-3] = lab_enc.fit_transform(X_train[:,-3])
X_train[:,-4] = lab_enc.fit_transform(X_train[:,-4])
#X_train = X_train[:,1:]

X_test = np.array(col_trns.fit_transform(X_test))
#X_test[:,-4] = lab_enc.fit_transform(X_test[:,-4])
X_test[:,-3] = lab_enc.fit_transform(X_test[:,-3])
X_test[:,-4] = lab_enc.fit_transform(X_test[:,-4])
#X_test = X_test[:,1:]

In [27]:
print(X_test[0])
print(len(X_test[0]))

[0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0 6 4 7]
16


In [28]:
#from sklearn.naive_bayes import GaussianNB
#classifier = GaussianNB()
#classifier.fit(X_train, y_train)

In [29]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs', max_iter=10000)
classifier.fit(X_train, y_train) 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [30]:
test_pred = classifier.predict(X_test)
print(test_pred.reshape(len(test_pred), 1))
print(np.unique(test_pred, return_counts=True))

[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
(array([0, 1]), array([   9, 7961]))
